# This file is auto-generated. Do not edit manually.
# Source: data/generated/templates/*.json
# Generated by: scripts/generate_tflocals.py

locals {
  # Resource naming constraints (generated)
  # Map of Terraform key to rule object
  # Use local._rules to access this data
  _rules = {
    key_vault = {
      arm_type     = "Microsoft.KeyVault/vaults"
      abbreviation = "kv"
      min_length   = 3
      max_length   = 24
      pattern      = "^[a-zA-Z0-9-]{3,24}$"
      scope        = "global"
    }
    storage_account = {
      arm_type     = "Microsoft.Storage/storageAccounts"
      abbreviation = "st"
      min_length   = 3
      max_length   = 24
      pattern      = "^[a-z0-9]+$"
      scope        = "global"
    }
  }
}
