# This file is auto-generated. Do not edit manually.
# Source: data/generated/templates/*.json
# Generated by: scripts/generate_tflocals.py

locals {
  # Terraform key to Azure ARM resource type mapping (generated)
  # Data-plane resources have null value
  # Use local._resource_types to access this data
  _resource_types = {
    key_vault       = "Microsoft.KeyVault/vaults"
    storage_account = "Microsoft.Storage/storageAccounts"
  }
}
