# This file is auto-generated. Do not edit manually.
# Source: data/generated/templates/*.json
# Generated by: scripts/generate_tflocals.py

locals {
  # CAF-compliant resource type abbreviations (generated)
  # Map of Terraform key to abbreviation string
  # Use local._abbreviations to access this data
  _abbreviations = {
    key_vault       = "kv" # Microsoft.KeyVault/vaults
    storage_account = "st" # Microsoft.Storage/storageAccounts
  }
}
